# 1.Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
m,n=map(int,input('Enter the size of matrices ').split())
l1= list(map(int,input('Enter the elements of matrix1 ').split()))
l2= list(map(int,input('Enter the elements of matrix2 ').split()))
if len(l1)== m*n and len(l2)==m*n:
    m1= (np.array(l1)).reshape(m,n)
    m2= (np.array(l2)).reshape(m,n)
    print('The first matrix is\n',m1)
    print('The second matrix is\n',m2)
    print('The sum of two matrices is\n', m1+m2)
else:
    print('You have entered wrong number of elements. ')

Enter the size of matrices 2 2
Enter the elements of matrix1 1 2 3 4
Enter the elements of matrix2 5 6 3 4
The first matrix is
 [[1 2]
 [3 4]]
The second matrix is
 [[5 6]
 [3 4]]
The sum of two matrices is
 [[6 8]
 [6 8]]


# 2. Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np
m1,n1=map(int,input('Enter the size of matrix1 ').split())
m2,n2=map(int,input('Enter the size of matrix2 ').split())
l1= list(map(int,input('Enter the elements of matrix1 ').split()))
l2= list(map(int,input('Enter the elements of matrix2 ').split()))
if len(l1)== m1*n1 and len(l2)==m2*n2:
    mat1= (np.array(l1)).reshape(m1,n1)
    mat2= (np.array(l2)).reshape(m2,n2)
    if n1==m2:
        
        print('The first matrix is\n',mat1)
        print('The second matrix is\n',mat2)
        print('The product of two matrices is\n', mat1@mat2)
    else:
        print('Multiplication of matrices cannot be done. ')
else:
    print('You have entered wrong number of elements. ')

Enter the size of matrix1 3 2
Enter the size of matrix2 2 3
Enter the elements of matrix1 1 2 3 4 5 6
Enter the elements of matrix2 2 1 3 4 5 6
The first matrix is
 [[1 2]
 [3 4]
 [5 6]]
The second matrix is
 [[2 1 3]
 [4 5 6]]
The product of two matrices is
 [[10 11 15]
 [22 23 33]
 [34 35 51]]


# 3.  Write a Python Program to Transpose a Matrix? 

In [4]:
import numpy as np
m,n=map(int,input('Enter the size of matrix ').split())
l1= list(map(int,input('Enter the elements of matrix ').split()))
if len(l1)==m*n:
    m1= (np.array(l1)).reshape(m,n)
    print('The original matrix is\n',m1)
    res=np.transpose(m1)
    print('The transposed matrix is\n',res)
else:
    print('You have entered wrong number of elements')
    
    

Enter the size of matrix 2 4
Enter the elements of matrix 1 2 3 4 5 6 7 8
The original matrix is
 [[1 2 3 4]
 [5 6 7 8]]
The transposed matrix is
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
line= input('Enter a string ')
line.casefold()
res= line.split()
res.sort()

print('The string after sorting words in Alphabetical order : ',' '.join(res))

Enter a string hiii please convert this string into alphabetical order
The string after sorting words in Alphabetical order :  alphabetical convert hiii into order please string this


# 5. Write a Python Program to Remove Punctuation From a String?

In [8]:
line= input('Enter a string')
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
res=""
for i in line:
    if i not in punc:
        res=res+i
print('The string after removing Punctuation from the string : ',res)
        

Enter a stringPl%$ease rem(o)ve the <Punc>tua/ion
The string after removing Punctuation from the string :  Please remove the Punctuaion
